Vz.Widgets = Vz.Widgets || {};
Vz.Widgets.countryContinentNEW = {
    "AD" : "EU",
    "AX" : "EU",
    "AL" : "EU",
    "BY" : "EU",
    "BG" : "EU",
    "CZ" : "EU",
    "ES" : "EU",
    "GE" : "EU",
    "GG" : "EU",
    "HU" : "EU",
    "IM" : "EU",
    "MD" : "EU",
    "PL" : "EU",
    "RO" : "EU",
    "RU" : "EU",
    "SK" : "EU",
    "UA" : "EU",
    "AM" : "EU",
    "AZ" : "EU",
    "KZ" : "EU",
    "KG" : "EU",
    "TJ" : "EU",
    "TM" : "EU",
    "UZ" : "EU",
    "DK" : "EU",
    "EE" : "EU",
    "FO" : "EU",
    "FI" : "EU",
    "IS" : "EU",
    "LV" : "EU",
    "LI" : "EU",
    "LT" : "EU",
    "NO" : "EU",
    "SE" : "EU",
    "SJ" : "EU",
    "BA" : "EU",
    "HR" : "EU",
    "CY" : "EU",
    "GI" : "EU",
    "GR" : "EU",
    "IT" : "EU",
    "JE" : "EU",
    "XK" : "EU",
    "MT" : "EU",
    "MK" : "EU",
    "MC" : "EU",
    "ME" : "EU",
    "PT" : "EU",
    "RS" : "EU",
    "SI" : "EU",
    "SM" : "EU",
    "TR" : "EU",
    "AT" : "EU",
    "BE" : "EU",
    "FR" : "EU",
    "DE" : "EU",
    "IE" : "EU",
    "LU" : "EU",
    "NL" : "EU",
    "CH" : "EU",
    "GB" : "EU",
    "VA" : "EU",
    "DZ" : "MEA",
    "BH" : "MEA",
    "EH" : "MEA",
    "EG" : "MEA",
    "IR" : "MEA",
    "IQ" : "MEA",
    "IL" : "MEA",
    "JO" : "MEA",
    "KW" : "MEA",
    "LB" : "MEA",
    "LY" : "MEA",
    "MA" : "MEA",
    "OM" : "MEA",
    "PS" : "MEA",
    "QA" : "MEA",
    "SA" : "MEA",
    "SS" : "MEA",
    "SD" : "MEA",
    "SY" : "MEA",
    "TN" : "MEA",
    "AE" : "MEA",
    "YE" : "MEA",
    "BI" : "MEA",
    "DJ" : "MEA",
    "ER" : "MEA",
    "ET" : "MEA",
    "KE" : "MEA",
    "RW" : "MEA",
    "SO" : "MEA",
    "TZ" : "MEA",
    "UG" : "MEA",
    "CM" : "MEA",
    "CF" : "MEA",
    "TD" : "MEA",
    "CD" : "MEA",
    "CG" : "MEA",
    "GQ" : "MEA",
    "GA" : "MEA",
    "ST" : "MEA",
    "AO" : "MEA",
    "BW" : "MEA",
    "KM" : "MEA",
    "SZ" : "MEA",
    "SN" : "MEA",
    "LS" : "MEA",
    "MG" : "MEA",
    "MW" : "MEA",
    "MU" : "MEA",
    "MZ" : "MEA",
    "NA" : "MEA",
    "SC" : "MEA",
    "ZA" : "MEA",
    "ZM" : "MEA",
    "ZW" : "MEA",
    "BJ" : "MEA",
    "BF" : "MEA",
    "CV" : "MEA",
    "GM" : "MEA",
    "GH" : "MEA",
    "GN" : "MEA",
    "GW" : "MEA",
    "CI" : "MEA",
    "LR" : "MEA",
    "ML" : "MEA",
    "MR" : "MEA",
    "NE" : "MEA",
    "NG" : "MEA",
    "RE" : "MEA",
    "SH" : "MEA",
    "SL" : "MEA",
    "TG" : "MEA",
    "YT" : "MEA",
    "AF" : "APAC",
    "AS" : "APAC",
    "AU" : "APAC",
    "BD" : "APAC",
    "DB" : "APAC",
    "BN" : "APAC",
    "BT" : "APAC",
    "CC" : "APAC",
    "CN" : "APAC",
    "CK" : "APAC",
    "CX" : "APAC",
    "FJ" : "APAC",
    "FM" : "APAC",
    "GU" : "APAC",
    "HK" : "APAC",
    "ID" : "APAC",
    "IN" : "APAC",
    "IO" : "APAC",
    "JP" : "APAC",
    "KH" : "APAC",
    "KI" : "APAC",
    "KP" : "APAC",
    "KR" : "APAC",
    "LA" : "APAC",
    "LK" : "APAC",
    "MH" : "APAC",
    "MM" : "APAC",
    "MN" : "APAC",
    "MO" : "APAC",
    "MP" : "APAC",
    "MV" : "APAC",
    "MY" : "APAC",
    "NC" : "APAC",
    "NF" : "APAC",
    "NP" : "APAC",
    "NR" : "APAC",
    "NU" : "APAC",
    "NZ" : "APAC",
    "PG" : "APAC",
    "PF" : "APAC",
    "PH" : "APAC",
    "PK" : "APAC",
    "PN" : "APAC",
    "PW" : "APAC",
    "SB" : "APAC",
    "SG" : "APAC",
    "TH" : "APAC",
    "TK" : "APAC",
    "TL" : "APAC",
    "TO" : "APAC",
    "TV" : "APAC",
    "TW" : "APAC",
    "UM" : "APAC",
    "VN" : "APAC",
    "VU" : "APAC",
    "WS" : "APAC",
    "WF" : "APAC",
    "AG" : "LATAM",
    "AI" : "LATAM",
    "AR" : "LATAM",
    "AW" : "LATAM",
    "BB" : "LATAM",
    "BM" : "LATAM",
    "BO" : "LATAM",
    "BL" : "LATAM",
    "BR" : "LATAM",
    "BS" : "LATAM",
    "BZ" : "LATAM",
    "CL" : "LATAM",
    "CO" : "LATAM",
    "CR" : "LATAM",
    "CU" : "LATAM",
    "CW" : "LATAM",
    "DM" : "LATAM",
    "DO" : "LATAM",
    "EC" : "LATAM",
    "FK" : "LATAM",
    "GD" : "LATAM",
    "GS" : "LATAM",
    "GT" : "LATAM",
    "GF" : "LATAM",
    "GY" : "LATAM",
    "GL" : "LATAM",
    "GP" : "LATAM",
    "HN" : "LATAM",
    "HT" : "LATAM",
    "JM" : "LATAM",
    "KN" : "LATAM",
    "KY" : "LATAM",
    "LC" : "LATAM",
    "MF" : "LATAM",
    "MS" : "LATAM",
    "MX" : "LATAM",
    "MQ" : "LATAM",
    "NI" : "LATAM",
    "PA" : "LATAM",
    "PE" : "LATAM",
    "PM" : "LATAM",
    "PR" : "LATAM",
    "PY" : "LATAM",
    "SR" : "LATAM",
    "SV" : "LATAM",
    "TC" : "LATAM",
    "TT" : "LATAM",
    "UY" : "LATAM",
    "VC" : "LATAM",
    "VE" : "LATAM",
    "VG" : "LATAM",
    "VI" : "LATAM",
    "CA" : "NAMER",
    "US" : "NAMER",
};
Vz.Widgets.countryContinent = {
    "AD": "EU",
    "AE": "AS",
    "AF": "AS",
    "AG": "USA",
    "AI": "USA",
    "AL": "EU",
    "AM": "AS",
    "AN": "USA",
    "AO": "AF",
    "AQ": "AN",
    "AR": "USA",
    "AS": "OC",
    "AT": "EU",
    "AU": "OC",
    "AW": "USA",
    "AX": "EU",
    "AZ": "AS",
    "BA": "EU",
    "BB": "USA",
    "BD": "AS",
    "BE": "EU",
    "BF": "AF",
    "BG": "EU",
    "BH": "AS",
    "BI": "AF",
    "BJ": "AF",
    "BL": "USA",
    "BM": "USA",
    "BN": "AS",
    "BO": "USA",
    "BQ": "USA",
    "BR": "USA",
    "BS": "USA",
    "BT": "AS",
    "BV": "AN",
    "BW": "AF",
    "BY": "EU",
    "BZ": "USA",
    "CA": "USA",
    "CC": "AS",
    "CD": "AF",
    "CF": "AF",
    "CG": "AF",
    "CH": "EU",
    "CI": "AF",
    "CK": "OC",
    "CL": "USA",
    "CM": "AF",
    "CN": "AS",
    "CO": "USA",
    "CR": "USA",
    "CS": "EU",
    "CU": "USA",
    "CV": "AF",
    "CW": "USA",
    "CX": "AS",
    "CY": "EU",
    "CZ": "EU",
    "DE": "EU",
    "DJ": "AF",
    "DK": "EU",
    "DM": "USA",
    "DO": "USA",
    "DZ": "AF",
    "EC": "USA",
    "EE": "EU",
    "EG": "AF",
    "EH": "AF",
    "ER": "AF",
    "ES": "EU",
    "ET": "AF",
    "FI": "EU",
    "FJ": "OC",
    "FK": "USA",
    "FM": "OC",
    "FO": "EU",
    "FR": "EU",
    "GA": "AF",
    "GB": "EU",
    "GD": "USA",
    "GE": "AS",
    "GF": "USA",
    "GG": "EU",
    "GH": "AF",
    "GI": "EU",
    "GL": "USA",
    "GM": "AF",
    "GN": "AF",
    "GP": "USA",
    "GQ": "AF",
    "GR": "EU",
    "GS": "AN",
    "GT": "USA",
    "GU": "OC",
    "GW": "AF",
    "GY": "USA",
    "HK": "AS",
    "HM": "AN",
    "HN": "USA",
    "HR": "EU",
    "HT": "USA",
    "HU": "EU",
    "ID": "AS",
    "IE": "EU",
    "IL": "AS",
    "IM": "EU",
    "IN": "AS",
    "IO": "AS",
    "IQ": "AS",
    "IR": "AS",
    "IS": "EU",
    "IT": "EU",
    "JE": "EU",
    "JM": "USA",
    "JO": "AS",
    "JP": "AS",
    "KE": "AF",
    "KG": "AS",
    "KH": "AS",
    "KI": "OC",
    "KM": "AF",
    "KN": "USA",
    "KP": "AS",
    "KR": "AS",
    "KW": "AS",
    "KY": "USA",
    "KZ": "AS",
    "LA": "AS",
    "LB": "AS",
    "LC": "USA",
    "LI": "EU",
    "LK": "AS",
    "LR": "AF",
    "LS": "AF",
    "LT": "EU",
    "LU": "EU",
    "LV": "EU",
    "LY": "AF",
    "MA": "AF",
    "MC": "EU",
    "MD": "EU",
    "ME": "EU",
    "MF": "USA",
    "MG": "AF",
    "MH": "OC",
    "MK": "EU",
    "ML": "AF",
    "MM": "AS",
    "MN": "AS",
    "MO": "AS",
    "MP": "OC",
    "MQ": "USA",
    "MR": "AF",
    "MS": "USA",
    "MT": "EU",
    "MU": "AF",
    "MV": "AS",
    "MW": "AF",
    "MX": "USA",
    "MY": "AS",
    "MZ": "AF",
    "NA": "AF",
    "NC": "OC",
    "NE": "AF",
    "NF": "OC",
    "NG": "AF",
    "NI": "USA",
    "NL": "EU",
    "NO": "EU",
    "NP": "AS",
    "NR": "OC",
    "NU": "OC",
    "NZ": "OC",
    "OM": "AS",
    "PA": "USA",
    "PE": "USA",
    "PF": "OC",
    "PG": "OC",
    "PH": "AS",
    "PK": "AS",
    "PL": "EU",
    "PM": "USA",
    "PN": "OC",
    "PR": "USA",
    "PS": "AS",
    "PT": "EU",
    "PW": "OC",
    "PY": "USA",
    "QA": "AS",
    "RE": "AF",
    "RO": "EU",
    "RS": "EU",
    "RU": "EU",
    "RW": "AF",
    "SA": "AS",
    "SB": "OC",
    "SC": "AF",
    "SD": "AF",
    "SE": "EU",
    "SG": "AS",
    "SH": "AF",
    "SI": "EU",
    "SJ": "EU",
    "SK": "EU",
    "SL": "AF",
    "SM": "EU",
    "SN": "AF",
    "SO": "AF",
    "SR": "USA",
    "SS": "AF",
    "ST": "AF",
    "SV": "USA",
    "SX": "USA",
    "SY": "AS",
    "SZ": "AF",
    "TC": "USA",
    "TD": "AF",
    "TF": "AN",
    "TG": "AF",
    "TH": "AS",
    "TJ": "AS",
    "TK": "OC",
    "TL": "OC",
    "TM": "AS",
    "TN": "AF",
    "TO": "OC",
    "TR": "AS",
    "TT": "USA",
    "TV": "OC",
    "TW": "AS",
    "TZ": "AF",
    "UA": "EU",
    "UG": "AF",
    "UM": "OC",
    "US": "USA",
    "UY": "USA",
    "UZ": "AS",
    "VA": "EU",
    "VC": "USA",
    "VE": "USA",
    "VG": "USA",
    "VI": "USA",
    "VN": "AS",
    "VU": "OC",
    "WF": "OC",
    "WS": "OC",
    "XK": "EU",
    "YE": "AS",
    "YT": "AF",
    "ZA": "AF",
    "ZM": "AF",
    "ZW": "AF"
};
Vz.Widgets.continent = {
    "EU": "Europe",
    "AS": "Asia",
    "USA": "America",
    "OC": "Oceania",
    "AF": "Africa"
};
Vz.Widgets.continentNEW = {
    "EU": "Europe",
    "MEA": "Middle East & Africa",
    "APAC": "Asia Pacific",
    "LATAM": "South America",
    "NAMER": "North America",
};