Vz.Widgets = Vz.Widgets || {};
Vz.Widgets.countryContinent = {
    "AD" : "EU",
    "AX" : "EU",
    "AL" : "EU",
    "BY" : "EU",
    "BG" : "EU",
    "CZ" : "EU",
    "ES" : "EU",
    "GE" : "EU",
    "GG" : "EU",
    "HU" : "EU",
    "IM" : "EU",
    "MD" : "EU",
    "PL" : "EU",
    "RO" : "EU",
    "RU" : "EU",
    "SK" : "EU",
    "UA" : "EU",
    "AM" : "EU",
    "AZ" : "EU",
    "KZ" : "EU",
    "KG" : "EU",
    "TJ" : "EU",
    "TM" : "EU",
    "UZ" : "EU",
    "DK" : "EU",
    "EE" : "EU",
    "FO" : "EU",
    "FI" : "EU",
    "IS" : "EU",
    "LV" : "EU",
    "LI" : "EU",
    "LT" : "EU",
    "NO" : "EU",
    "SE" : "EU",
    "SJ" : "EU",
    "BA" : "EU",
    "HR" : "EU",
    "CY" : "EU",
    "GI" : "EU",
    "GR" : "EU",
    "IT" : "EU",
    "JE" : "EU",
    "XK" : "EU",
    "MT" : "EU",
    "MK" : "EU",
    "MC" : "EU",
    "ME" : "EU",
    "PT" : "EU",
    "RS" : "EU",
    "SI" : "EU",
    "SM" : "EU",
    "TR" : "EU",
    "AT" : "EU",
    "BE" : "EU",
    "FR" : "EU",
    "DE" : "EU",
    "IE" : "EU",
    "LU" : "EU",
    "NL" : "EU",
    "CH" : "EU",
    "GB" : "EU",
    "VA" : "EU",
    "DZ" : "MEA",
    "BH" : "MEA",
    "EH" : "MEA",
    "EG" : "MEA",
    "IR" : "MEA",
    "IQ" : "MEA",
    "IL" : "MEA",
    "JO" : "MEA",
    "KW" : "MEA",
    "LB" : "MEA",
    "LY" : "MEA",
    "MA" : "MEA",
    "OM" : "MEA",
    "PS" : "MEA",
    "QA" : "MEA",
    "SA" : "MEA",
    "SS" : "MEA",
    "SD" : "MEA",
    "SY" : "MEA",
    "TN" : "MEA",
    "AE" : "MEA",
    "YE" : "MEA",
    "BI" : "MEA",
    "DJ" : "MEA",
    "ER" : "MEA",
    "ET" : "MEA",
    "KE" : "MEA",
    "RW" : "MEA",
    "SO" : "MEA",
    "TZ" : "MEA",
    "UG" : "MEA",
    "CM" : "MEA",
    "CF" : "MEA",
    "TD" : "MEA",
    "CD" : "MEA",
    "CG" : "MEA",
    "GQ" : "MEA",
    "GA" : "MEA",
    "ST" : "MEA",
    "AO" : "MEA",
    "BW" : "MEA",
    "KM" : "MEA",
    "SZ" : "MEA",
    "SN" : "MEA",
    "LS" : "MEA",
    "MG" : "MEA",
    "MW" : "MEA",
    "MU" : "MEA",
    "MZ" : "MEA",
    "NA" : "MEA",
    "SC" : "MEA",
    "ZA" : "MEA",
    "ZM" : "MEA",
    "ZW" : "MEA",
    "BJ" : "MEA",
    "BF" : "MEA",
    "CV" : "MEA",
    "GM" : "MEA",
    "GH" : "MEA",
    "GN" : "MEA",
    "GW" : "MEA",
    "CI" : "MEA",
    "LR" : "MEA",
    "ML" : "MEA",
    "MR" : "MEA",
    "NE" : "MEA",
    "NG" : "MEA",
    "RE" : "MEA",
    "SH" : "MEA",
    "SL" : "MEA",
    "TG" : "MEA",
    "YT" : "MEA",
    "AF" : "APAC",
    "AS" : "APAC",
    "AU" : "APAC",
    "BD" : "APAC",
    "DB" : "APAC",
    "BN" : "APAC",
    "BT" : "APAC",
    "CC" : "APAC",
    "CN" : "APAC",
    "CK" : "APAC",
    "CX" : "APAC",
    "FJ" : "APAC",
    "FM" : "APAC",
    "GU" : "APAC",
    "HK" : "APAC",
    "ID" : "APAC",
    "IN" : "APAC",
    "IO" : "APAC",
    "JP" : "APAC",
    "KH" : "APAC",
    "KI" : "APAC",
    "KP" : "APAC",
    "KR" : "APAC",
    "LA" : "APAC",
    "LK" : "APAC",
    "MH" : "APAC",
    "MM" : "APAC",
    "MN" : "APAC",
    "MO" : "APAC",
    "MP" : "APAC",
    "MV" : "APAC",
    "MY" : "APAC",
    "NC" : "APAC",
    "NF" : "APAC",
    "NP" : "APAC",
    "NR" : "APAC",
    "NU" : "APAC",
    "NZ" : "APAC",
    "PG" : "APAC",
    "PF" : "APAC",
    "PH" : "APAC",
    "PK" : "APAC",
    "PN" : "APAC",
    "PW" : "APAC",
    "SB" : "APAC",
    "SG" : "APAC",
    "TH" : "APAC",
    "TK" : "APAC",
    "TL" : "APAC",
    "TO" : "APAC",
    "TV" : "APAC",
    "TW" : "APAC",
    "UM" : "APAC",
    "VN" : "APAC",
    "VU" : "APAC",
    "WS" : "APAC",
    "WF" : "APAC",
    "AG" : "LATAM",
    "AI" : "LATAM",
    "AR" : "LATAM",
    "AW" : "LATAM",
    "BB" : "LATAM",
    "BM" : "LATAM",
    "BO" : "LATAM",
    "BL" : "LATAM",
    "BR" : "LATAM",
    "BS" : "LATAM",
    "BZ" : "LATAM",
    "CL" : "LATAM",
    "CO" : "LATAM",
    "CR" : "LATAM",
    "CU" : "LATAM",
    "CW" : "LATAM",
    "DM" : "LATAM",
    "DO" : "LATAM",
    "EC" : "LATAM",
    "FK" : "LATAM",
    "GD" : "LATAM",
    "GS" : "LATAM",
    "GT" : "LATAM",
    "GF" : "LATAM",
    "GY" : "LATAM",
    "GL" : "LATAM",
    "GP" : "LATAM",
    "HN" : "LATAM",
    "HT" : "LATAM",
    "JM" : "LATAM",
    "KN" : "LATAM",
    "KY" : "LATAM",
    "LC" : "LATAM",
    "MF" : "LATAM",
    "MS" : "LATAM",
    "MX" : "LATAM",
    "MQ" : "LATAM",
    "NI" : "LATAM",
    "PA" : "LATAM",
    "PE" : "LATAM",
    "PM" : "LATAM",
    "PR" : "LATAM",
    "PY" : "LATAM",
    "SR" : "LATAM",
    "SV" : "LATAM",
    "TC" : "LATAM",
    "TT" : "LATAM",
    "UY" : "LATAM",
    "VC" : "LATAM",
    "VE" : "LATAM",
    "VG" : "LATAM",
    "VI" : "LATAM",
    "CA" : "NAMER",
    "US" : "NAMER",
};
Vz.Widgets.continent = {
    "EU": "Europe",
    "MEA": "Middle East & Africa",
    "APAC": "Asia Pacific",
    "LATAM": "South America",
    "NAMER": "North America",
};
Vz.Widgets.countries = {
    "AF":"Afghanistan",
    "AX":"Aland Islands",
    "AL":"Albania",
    "DZ":"Algeria",
    "AS":"American Samoa",
    "AD":"Andorra",
    "AO":"Angola",
    "AI":"Anguilla",
    "AG":"Antigua And Barbuda",
    "AR":"Argentina",
    "AM":"Armenia",
    "AW":"Aruba",
    "AU":"Australia",
    "AT":"Austria",
    "AZ":"Azerbaijan",
    "BS":"Bahamas",
    "BH":"Bahrain",
    "BD":"Bangladesh",
    "BB":"Barbados",
    "BE":"Belgium",
    "BZ":"Belize",
    "BJ":"Benin",
    "BM":"Bermuda",
    "BT":"Bhutan",
    "BO":"Bolivia",
    "BA":"Bosnia And Herzegovina",
    "BW":"Botswana",
    "BR":"Brazil",
    "IO":"British Indian Ocean Territory",
    "BN":"Brunei Darussalam",
    "BG":"Bulgaria",
    "BF":"Burkina Faso",
    "BI":"Burundi",
    "KH":"Cambodia",
    "CM":"Cameroon",
    "CA":"Canada",
    "CV":"Cape Verde",
    "KY":"Cayman Islands",
    "CF":"Central African Republic",
    "TD":"Chad",
    "CL":"Chile",
    "CN":"China",
    "CX":"Christmas Island",
    "CC":"Cocos (Keeling) Islands",
    "CO":"Colombia",
    "KM":"Comoros",
    "CG":"Congo",
    "CD":"Congo, Democratic Republic",
    "CK":"Cook Islands",
    "CR":"Costa Rica",
    "CI":"Cote D'Ivoire",
    "HR":"Croatia",
    "CW":"Curacao",
    "CY":"Cyprus",
    "CZ":"Czech Republic",
    "DK":"Denmark",
    "DJ":"Djibouti",
    "DM":"Dominica",
    "DO":"Dominican Republic",
    "EC":"Ecuador",
    "EG":"Egypt",
    "SV":"El Salvador",
    "GQ":"Equatorial Guinea",
    "ER":"Eritrea",
    "EE":"Estonia",
    "ET":"Ethiopia",
    "FK":"Falkland Islands (Malvinas)",
    "FO":"Faroe Islands",
    "FJ":"Fiji",
    "FI":"Finland",
    "FR":"France",
    "GF":"French Guiana",
    "PF":"French Polynesia",
    "GA":"Gabon",
    "GM":"Gambia",
    "GE":"Georgia",
    "DE":"Germany",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GR":"Greece",
    "GL":"Greenland",
    "GD":"Grenada",
    "GP":"Guadeloupe",
    "GU":"Guam",
    "GT":"Guatemala",
    "GG":"Guernsey",
    "GN":"Guinea",
    "GW":"Guinea-Bissau",
    "GY":"Guyana",
    "HT":"Haiti",
    "VA":"Holy See (Vatican City State)",
    "HN":"Honduras",
    "HK":"Hong Kong",
    "HU":"Hungary",
    "IS":"Iceland",
    "IN":"India",
    "ID":"Indonesia",
    "IQ":"Iraq",
    "IE":"Ireland",
    "IM":"Isle Of Man",
    "IL":"Israel",
    "IT":"Italy",
    "JM":"Jamaica",
    "JP":"Japan",
    "JE":"Jersey",
    "JO":"Jordan",
    "KZ":"Kazakhstan",
    "KE":"Kenya",
    "KI":"Kiribati",
    "KR":"South Korea",
    "XK":"Kosovo",
    "KW":"Kuwait",
    "KG":"Kyrgyzstan",
    "LA":"Lao People's Democratic Republic",
    "LV":"Latvia",
    "LB":"Lebanon",
    "LS":"Lesotho",
    "LR":"Liberia",
    "LY":"Libyan Arab Jamahiriya",
    "LI":"Liechtenstein",
    "LT":"Lithuania",
    "LU":"Luxembourg",
    "MO":"Macao",
    "MK":"Macedonia",
    "MG":"Madagascar",
    "MW":"Malawi",
    "MY":"Malaysia",
    "MV":"Maldives",
    "ML":"Mali",
    "MT":"Malta",
    "MH":"Marshall Islands",
    "MQ":"Martinique",
    "MR":"Mauritania",
    "MU":"Mauritius",
    "YT":"Mayotte",
    "MX":"Mexico",
    "FM":"Micronesia, Federated States Of",
    "MD":"Moldova",
    "MC":"Monaco",
    "MN":"Mongolia",
    "ME":"Montenegro",
    "MS":"Montserrat",
    "MA":"Morocco",
    "MZ":"Mozambique",
    "MM":"Myanmar",
    "NA":"Namibia",
    "NR":"Nauru",
    "NP":"Nepal",
    "NL":"Netherlands",
    "NC":"New Caledonia",
    "NZ":"New Zealand",
    "NI":"Nicaragua",
    "NE":"Niger",
    "NG":"Nigeria",
    "NU":"Niue",
    "NF":"Norfolk Island",
    "MP":"Northern Mariana Islands",
    "NO":"Norway",
    "OM":"Oman",
    "PK":"Pakistan",
    "PW":"Palau",
    "PS":"Palestine, State of",
    "PA":"Panama",
    "PG":"Papua New Guinea",
    "PY":"Paraguay",
    "PE":"Peru",
    "PH":"Philippines",
    "PL":"Poland",
    "PT":"Portugal",
    "PR":"Puerto Rico",
    "QA":"Qatar",
    "RE":"Reunion",
    "RO":"Romania",
    "RW":"Rwanda",
    "BL":"Saint Barthelemy",
    "SH":"Saint Helena",
    "KN":"Saint Kitts And Nevis",
    "LC":"Saint Lucia",
    "MF":"Saint Martin",
    "PM":"Saint Pierre And Miquelon",
    "VC":"Saint Vincent And Grenadines",
    "WS":"Samoa",
    "SM":"San Marino",
    "ST":"Sao Tome And Principe",
    "SA":"Saudi Arabia",
    "SN":"Senegal",
    "RS":"Serbia",
    "SC":"Seychelles",
    "SL":"Sierra Leone",
    "SG":"Singapore",
    "SK":"Slovakia",
    "SI":"Slovenia",
    "SB":"Solomon Islands",
    "SO":"Somalia",
    "ZA":"South Africa",
    "ES":"Spain",
    "LK":"Sri Lanka",
    "SS":"South Sudan",
    "SR":"Suriname",
    "SJ":"Svalbard And Jan Mayen",
    "SZ":"Swaziland",
    "SE":"Sweden",
    "CH":"Switzerland",
    "TW":"Taiwan",
    "TJ":"Tajikistan",
    "TZ":"Tanzania",
    "TH":"Thailand",
    "TL":"Timor-Leste",
    "TG":"Togo",
    "TK":"Tokelau",
    "TO":"Tonga",
    "TT":"Trinidad And Tobago",
    "TN":"Tunisia",
    "TR":"Turkey",
    "TM":"Turkmenistan",
    "TC":"Turks And Caicos Islands",
    "TV":"Tuvalu",
    "UG":"Uganda",
    "UA":"Ukraine",
    "AE":"United Arab Emirates",
    "GB":"United Kingdom",
    "US":"United States",
    "UY":"Uruguay",
    "UZ":"Uzbekistan",
    "VU":"Vanuatu",
    "VE":"Venezuela",
    "VN":"Viet Nam",
    "VG":"Virgin Islands, British",
    "VI":"Virgin Islands, U.S.",
    "WF":"Wallis And Futuna",
    "EH":"Western Sahara",
    "YE":"Yemen",
    "ZM":"Zambia",
    "ZW":"Zimbabwe",
};



